!/bin/bash

root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_iso_01.root\",\"col\",\"output/AmBe_1e7_iso_01_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_iso_02.root\",\"col\",\"output/AmBe_1e7_iso_02_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_iso_03.root\",\"col\",\"output/AmBe_1e7_iso_03_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_iso_04.root\",\"col\",\"output/AmBe_1e7_iso_04_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_iso_05.root\",\"col\",\"output/AmBe_1e7_iso_05_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_iso_06.root\",\"col\",\"output/AmBe_1e7_iso_06_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_iso_07.root\",\"col\",\"output/AmBe_1e7_iso_07_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_iso_08.root\",\"col\",\"output/AmBe_1e7_iso_08_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_iso_09.root\",\"col\",\"output/AmBe_1e7_iso_09_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_iso_10.root\",\"col\",\"output/AmBe_1e7_iso_10_col.csv\"\)

root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_posxShift_iso_01.root\",\"col\",\"output/AmBe_1e7_posxShift_iso_01_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_posxShift_iso_02.root\",\"col\",\"output/AmBe_1e7_posxShift_iso_02_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_posxShift_iso_03.root\",\"col\",\"output/AmBe_1e7_posxShift_iso_03_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_posxShift_iso_04.root\",\"col\",\"output/AmBe_1e7_posxShift_iso_04_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_posxShift_iso_05.root\",\"col\",\"output/AmBe_1e7_posxShift_iso_05_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_posxShift_iso_06.root\",\"col\",\"output/AmBe_1e7_posxShift_iso_06_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_posxShift_iso_07.root\",\"col\",\"output/AmBe_1e7_posxShift_iso_07_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_posxShift_iso_08.root\",\"col\",\"output/AmBe_1e7_posxShift_iso_08_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_posxShift_iso_09.root\",\"col\",\"output/AmBe_1e7_posxShift_iso_09_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_posxShift_iso_10.root\",\"col\",\"output/AmBe_1e7_posxShift_iso_10_col.csv\"\)

root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_negxShift_iso_01.root\",\"col\",\"output/AmBe_1e7_negxShift_iso_01_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_negxShift_iso_02.root\",\"col\",\"output/AmBe_1e7_negxShift_iso_02_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_negxShift_iso_03.root\",\"col\",\"output/AmBe_1e7_negxShift_iso_03_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_negxShift_iso_04.root\",\"col\",\"output/AmBe_1e7_negxShift_iso_04_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_negxShift_iso_05.root\",\"col\",\"output/AmBe_1e7_negxShift_iso_05_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_negxShift_iso_06.root\",\"col\",\"output/AmBe_1e7_negxShift_iso_06_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_negxShift_iso_07.root\",\"col\",\"output/AmBe_1e7_negxShift_iso_07_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_negxShift_iso_08.root\",\"col\",\"output/AmBe_1e7_negxShift_iso_08_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_negxShift_iso_09.root\",\"col\",\"output/AmBe_1e7_negxShift_iso_09_col.csv\"\)
root -b -q convert_root2csv.C\(\"../build2/AmBe_1e7_negxShift_iso_10.root\",\"col\",\"output/AmBe_1e7_negxShift_iso_10_col.csv\"\)
